config/routes.rb
Rails.application.routes.draw do
  root to: "alarms#index"
  resources :upvotes
  resources :alarms
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/alarm.rb
class Alarm < ApplicationRecord
  has_many :upvotes
  validates :message, length: { maximum: 200}, presence: true

  after_create :send_push_notification

  def send_push_notification
  	SendAlarmPushNotificationJob.perform_later id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/upvote.rb
class Upvote < ApplicationRecord
  belongs_to :alarm
end

app/controllers/alarms_controller.rb
class AlarmsController < ApplicationController
  before_action :set_alarm, only: [:show, :edit, :update, :destroy]

  # GET /alarms
  # GET /alarms.json
  def index
    @alarms = Alarm.all.order(created_at: :desc)
  end

  # GET /alarms/1
  # GET /alarms/1.json
  def show
  end

  # GET /alarms/new
  def new
    @alarm = Alarm.new
  end

  # GET /alarms/1/edit
  def edit
  end

  # POST /alarms
  # POST /alarms.json
  def create
    alarm_params[:message].upcase!
    @alarm = Alarm.new(alarm_params)
    if @alarm.save
      redirect_to @alarm, notice: 'Alarm was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /alarms/1
  # PATCH/PUT /alarms/1.json
  def update
    alarm_params[:message].upcase!
    if @alarm.update(alarm_params)
      redirect_to @alarm, notice: 'Alarm was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /alarms/1
  # DELETE /alarms/1.json
  def destroy
    if @alarm.destroy
      redirect_to alarms_url, notice: 'Alarm was successfully destroyed.'
    else
      render :edit
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alarm
      @alarm = Alarm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alarm_params
      params.require(:alarm).permit(:message)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/upvotes_controller.rb
class UpvotesController < ApplicationController
  before_action :set_upvote, only: [:show, :edit, :update, :destroy]

  # GET /upvotes
  # GET /upvotes.json
  def index
    @upvotes = Upvote.all
  end

  # GET /upvotes/1
  # GET /upvotes/1.json
  def show
  end

  # GET /upvotes/new
  def new
    @upvote = Upvote.new
  end

  # GET /upvotes/1/edit
  def edit
  end

  # POST /upvotes
  # POST /upvotes.json
  def create
    @upvote = Upvote.new(upvote_params)

    respond_to do |format|
      if @upvote.save
        format.html { redirect_to @upvote, notice: 'Upvote was successfully created.' }
        format.json { render :show, status: :created, location: @upvote }
      else
        format.html { render :new }
        format.json { render json: @upvote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /upvotes/1
  # PATCH/PUT /upvotes/1.json
  def update
    respond_to do |format|
      if @upvote.update(upvote_params)
        format.html { redirect_to @upvote, notice: 'Upvote was successfully updated.' }
        format.json { render :show, status: :ok, location: @upvote }
      else
        format.html { render :edit }
        format.json { render json: @upvote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /upvotes/1
  # DELETE /upvotes/1.json
  def destroy
    @upvote.destroy
    respond_to do |format|
      format.html { redirect_to upvotes_url, notice: 'Upvote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_upvote
      @upvote = Upvote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def upvote_params
      params.require(:upvote).permit(:alarm_id, :session_id)
    end
end

app/helpers/alarms_helper.rb
module AlarmsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/upvotes_helper.rb
module UpvotesHelper
end

app/views/alarms/_form.html.erb
<%= form_with(model: alarm, local: true) do |form| %>
  <% if alarm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(alarm.errors.count, "error") %> prohibited this alarm from being saved:</h2>

      <ul>
      <% alarm.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_area :message, id: :alarm_message, style: "text-transform: uppercase;" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/alarms/edit.html.erb
<h1>Editing Alarm</h1>

<%= render 'form', alarm: @alarm %>

<%= link_to 'Show', @alarm %> |
<%= link_to 'Destroy', @alarm, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', alarms_path %>

app/views/alarms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alarms</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alarms.each do |alarm| %>
      <tr>
        <td><%= alarm.message %></td>
        <td><%= link_to 'Show', alarm %></td>
        <td><%= link_to 'Edit', edit_alarm_path(alarm) %></td>
        <td><%= link_to 'Destroy', alarm, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alarm', new_alarm_path %>

app/views/alarms/new.html.erb
<h1>New Alarm</h1>

<%= render 'form', alarm: @alarm %>

<%= link_to 'Back', alarms_path %>

app/views/alarms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @alarm.message %>
</p>

<%= link_to 'Edit', edit_alarm_path(@alarm) %> |
<%= link_to 'Back', alarms_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Handshake</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/upvotes/_form.html.erb
<%= form_with(model: upvote, local: true) do |form| %>
  <% if upvote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(upvote.errors.count, "error") %> prohibited this upvote from being saved:</h2>

      <ul>
      <% upvote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :alarm_id %>
    <%= form.text_field :alarm_id, id: :upvote_alarm_id %>
  </div>

  <div class="field">
    <%= form.label :session_id %>
    <%= form.text_field :session_id, id: :upvote_session_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/upvotes/edit.html.erb
<h1>Editing Upvote</h1>

<%= render 'form', upvote: @upvote %>

<%= link_to 'Show', @upvote %> |
<%= link_to 'Back', upvotes_path %>

app/views/upvotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Upvotes</h1>

<table>
  <thead>
    <tr>
      <th>Alarm</th>
      <th>Session</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @upvotes.each do |upvote| %>
      <tr>
        <td><%= upvote.alarm %></td>
        <td><%= upvote.session_id %></td>
        <td><%= link_to 'Show', upvote %></td>
        <td><%= link_to 'Edit', edit_upvote_path(upvote) %></td>
        <td><%= link_to 'Destroy', upvote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Upvote', new_upvote_path %>

app/views/upvotes/new.html.erb
<h1>New Upvote</h1>

<%= render 'form', upvote: @upvote %>

<%= link_to 'Back', upvotes_path %>

app/views/upvotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Alarm:</strong>
  <%= @upvote.alarm %>
</p>

<p>
  <strong>Session:</strong>
  <%= @upvote.session_id %>
</p>

<%= link_to 'Edit', edit_upvote_path(@upvote) %> |
<%= link_to 'Back', upvotes_path %>